import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Richals",
  keywords: ["Space Invaders", "Chess", "Resume", "Game", "Next.js", "React"],
  authors: [
    {
      name: "Richals",
      url: "https://personal-project-sandy-iota.vercel.app/",
      email: "richalsthomask@gmail.com",
      github: "https://github.com/richalsthomask",
    },
  ],
  icons: {
    icon: "/r.png",
    shortcut: "/r.png",
    apple: "/r.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.png" type="image/png" />
        <title>My App</title>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
